// src/styles.js
export const s = {
  appBg: { minHeight: "100vh", background: "linear-gradient(135deg,#e8f5e9 0%,#f1f8e9 100%)", fontFamily: "'Segoe UI','SolaimanLipi',Arial,sans-serif", fontSize: 13 },
  nav: { background: "linear-gradient(90deg,#1b5e20,#2e7d32)", boxShadow: "0 2px 6px rgba(0,0,0,0.18)" },
  navInner: { maxWidth: 1200, margin: "0 auto", padding: "8px 12px", display: "flex", alignItems: "center", justifyContent: "space-between", boxSizing: "border-box" },
  navBrand: { display: "flex", flexDirection: "column" },
  navLogo: { color: "#fff", fontWeight: 700, fontSize: 16, letterSpacing: 1 },
  navSub: { color: "#a5d6a7", fontSize: 11, marginTop: 1 },
  newBtn: { background: "#fff", color: "#1b5e20", border: "none", borderRadius: 7, padding: "6px 12px", fontWeight: 700, fontSize: 12, cursor: "pointer" },
  newBtn2: { background: "#2e7d32", color: "#fff", border: "none", borderRadius: 7, padding: "6px 12px", fontWeight: 700, fontSize: 12, cursor: "pointer" },
  backBtn2: { background: "#e8f5e9", color: "#1b5e20", border: "none", borderRadius: 6, padding: "5px 12px", fontSize: 12, cursor: "pointer" },
  tabBar: { background: "#fff", borderBottom: "2px solid #c8e6c9" },
  tabBarInner: { maxWidth: 1200, margin: "0 auto", display: "flex", boxSizing: "border-box" },
  tabBtn: { flex: 1, padding: "8px 4px", border: "none", background: "transparent", color: "#777", fontSize: 12, cursor: "pointer", fontWeight: 500 },
  tabActive: { flex: 1, padding: "8px 4px", border: "none", borderBottom: "3px solid #2e7d32", background: "transparent", color: "#1b5e20", fontSize: 12, cursor: "pointer", fontWeight: 700 },
  container: { maxWidth: 1200, margin: "0 auto", padding: "10px 8px", boxSizing: "border-box" },
  cardGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(250px,1fr))", gap: 10 },
  orderCard: { background: "#fff", borderRadius: 10, boxShadow: "0 2px 8px rgba(46,125,50,0.10)", padding: 10, border: "1px solid #c8e6c9" },
  cardTop: { display: "flex", justifyContent: "space-between", marginBottom: 4 },
  cardOrderNo: { fontSize: 11, color: "#388e3c", fontWeight: 700 },
  cardName: { fontSize: 14, fontWeight: 700, color: "#1a1a1a", marginTop: 1 },
  cardDate: { fontSize: 11, color: "#777" },
  cardCourier: { fontSize: 11, color: "#555", marginTop: 1 },
  cardBranch: { fontSize: 10, color: "#888", marginTop: 1 },
  cardPhone: { fontSize: 12, color: "#444", marginBottom: 2 },
  cardProducts: { fontSize: 11, color: "#555", marginBottom: 6, lineHeight: 1.5 },
  cardFooter: { display: "flex", justifyContent: "space-between", alignItems: "center", borderTop: "1px solid #e8f5e9", paddingTop: 6 },
  cardTotal: { fontWeight: 700, fontSize: 14, color: "#1b5e20" },
  viewBtn: { background: "#e8f5e9", color: "#1b5e20", border: "none", borderRadius: 5, padding: "4px 8px", cursor: "pointer", fontWeight: 600, fontSize: 11 },
  dlBtn: { background: "#e3f2fd", color: "#1565c0", border: "none", borderRadius: 5, padding: "4px 8px", cursor: "pointer", fontSize: 11 },
  dlBtn2: { background: "#1565c0", color: "#fff", border: "none", borderRadius: 7, padding: "7px 14px", cursor: "pointer", fontWeight: 700, fontSize: 12 },
  deleteBtn: { background: "#ffebee", color: "#c62828", border: "none", borderRadius: 5, padding: "4px 8px", cursor: "pointer", fontWeight: 600, fontSize: 11 },
  empty: { textAlign: "center", padding: "40px 20px", color: "#aaa", fontSize: 13, display: "flex", flexDirection: "column", alignItems: "center", gap: 8 },
  formCard: { background: "#fff", borderRadius: 12, boxShadow: "0 4px 20px rgba(46,125,50,0.12)", overflow: "hidden" },
  formHeader: { background: "linear-gradient(90deg,#1b5e20,#388e3c)", padding: "10px 14px", textAlign: "center" },
  logo: { color: "#fff", fontSize: 18, fontWeight: 800, letterSpacing: 2 },
  logoSub: { color: "#a5d6a7", fontSize: 11, marginTop: 1 },
  metaGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))", gap: 8, padding: "10px 10px 0" },
  section: { padding: "8px 10px" },
  sectionTitle: { fontWeight: 700, fontSize: 12, color: "#2e7d32", marginBottom: 7, borderBottom: "2px solid #e8f5e9", paddingBottom: 3 },
  fieldGroup: { display: "flex", flexDirection: "column", gap: 3 },
  label: { fontSize: 11, color: "#555", fontWeight: 600 },
  input: { border: "1.5px solid #c8e6c9", borderRadius: 6, padding: "6px 8px", fontSize: 13, outline: "none", width: "100%", boxSizing: "border-box", fontFamily: "inherit", background: "#fafff8" },
  tableWrapper: { width: "100%" },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 12 },
  thead: { background: "#e8f5e9" },
  th: { padding: "6px 4px", textAlign: "left", fontWeight: 700, color: "#1b5e20", fontSize: 11, borderBottom: "2px solid #c8e6c9" },
  td: { padding: "4px 3px", verticalAlign: "middle", borderBottom: "1px solid #f1f8e9", overflow: "hidden" },
  trEven: { background: "#fff" },
  trOdd: { background: "#f9fdf9" },
  cellSelect: { border: "1px solid #d0ecd0", borderRadius: 4, padding: "4px 2px", fontSize: 11, width: "100%", boxSizing: "border-box", outline: "none", fontFamily: "inherit", background: "#fff" },
  cellInput: { border: "1px solid #d0ecd0", borderRadius: 4, padding: "4px 4px", fontSize: 11, width: "100%", boxSizing: "border-box", outline: "none", fontFamily: "inherit", background: "transparent" },
  removeBtn: { background: "#ffebee", color: "#c62828", border: "none", borderRadius: 4, padding: "2px 5px", cursor: "pointer", fontSize: 10 },
  addRowBtn: { marginTop: 7, background: "#e8f5e9", color: "#1b5e20", border: "1px dashed #81c784", borderRadius: 6, padding: "6px 12px", cursor: "pointer", fontSize: 12, fontWeight: 600, width: "100%" },
  totalBox: { display: "flex", justifyContent: "space-between", alignItems: "center", background: "linear-gradient(90deg,#e8f5e9,#f1f8e9)", border: "2px solid #81c784", borderRadius: 8, padding: "9px 12px", marginTop: 9 },
  totalLabel: { fontWeight: 700, fontSize: 13, color: "#1b5e20" },
  totalValue: { fontWeight: 800, fontSize: 18, color: "#1b5e20" },
  btnRow: { display: "flex", gap: 8, padding: "8px 10px 12px", justifyContent: "flex-end", flexWrap: "wrap" },
  cancelBtn: { background: "#f5f5f5", color: "#555", border: "1px solid #ddd", borderRadius: 7, padding: "7px 12px", cursor: "pointer", fontWeight: 600, fontSize: 12 },
  saveBtn: { background: "#2e7d32", color: "#fff", border: "none", borderRadius: 7, padding: "7px 16px", cursor: "pointer", fontWeight: 700, fontSize: 12 },
  printBtn: { background: "#1565c0", color: "#fff", border: "none", borderRadius: 7, padding: "7px 16px", cursor: "pointer", fontWeight: 700, fontSize: 12 },
  tabBtnSettings: { flex: "unset", padding: "8px 18px" },
  syncBadge: { fontSize: 10, padding: "2px 8px", borderRadius: 10, fontWeight: 700, display: "inline-block" },
  confirmBox: { background: "#fff", borderRadius: 12, padding: "20px 18px", maxWidth: 320, width: "100%", boxShadow: "0 8px 30px rgba(0,0,0,0.3)" },
  confirmMsg: { fontSize: 14, color: "#222", marginBottom: 18, lineHeight: 1.5, textAlign: "center" },
  confirmBtnRow: { display: "flex", gap: 8, justifyContent: "center" },
  confirmDeleteBtn: { background: "#c62828", color: "#fff", border: "none", borderRadius: 7, padding: "8px 18px", cursor: "pointer", fontWeight: 700, fontSize: 13 },
  confirmGreenBtn: { background: "#2e7d32", color: "#fff", border: "none", borderRadius: 7, padding: "8px 18px", cursor: "pointer", fontWeight: 700, fontSize: 13 },
  confirmBlueBtn: { background: "#1565c0", color: "#fff", border: "none", borderRadius: 7, padding: "8px 18px", cursor: "pointer", fontWeight: 700, fontSize: 13 },
  confirmPurpleBtn: { background: "#6a1b9a", color: "#fff", border: "none", borderRadius: 7, padding: "8px 18px", cursor: "pointer", fontWeight: 700, fontSize: 13 },
  // ---- Order Status Checkboxes (OrderCard) ----
  statusRow: { display: "flex", flexDirection: "column", gap: 5, padding: "6px 0 6px", borderTop: "1px solid #f0f7f0", marginTop: 5, marginBottom: 4 },
  statusLabel: { display: "flex", alignItems: "center", gap: 7, cursor: "pointer", userSelect: "none" },
  statusCheckbox: { width: 16, height: 16, cursor: "pointer", flexShrink: 0, accentColor: "#2e7d32" },
  statusText: { fontSize: 11, fontWeight: 600, lineHeight: 1.3 },
};

export const r = {
  tabRow: { display: "flex", gap: 6, marginBottom: 10 },
  tab: { background: "#f0f0f0", border: "none", borderRadius: 20, padding: "5px 12px", fontSize: 12, cursor: "pointer", color: "#555" },
  tabActive: { background: "#2e7d32", border: "none", borderRadius: 20, padding: "5px 12px", fontSize: 12, cursor: "pointer", color: "#fff", fontWeight: 700 },
  kpiRow: { display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 8, marginBottom: 10 },
  kpi: { background: "#fff", borderRadius: 10, padding: "10px 8px", textAlign: "center", boxShadow: "0 2px 6px rgba(46,125,50,0.10)", border: "1px solid #c8e6c9" },
  kpiVal: { fontWeight: 800, fontSize: 16, color: "#1b5e20" },
  kpiLabel: { fontSize: 10, color: "#777", marginTop: 2 },
  card: { background: "#fff", borderRadius: 10, padding: "10px", marginBottom: 10, boxShadow: "0 2px 6px rgba(46,125,50,0.10)", border: "1px solid #c8e6c9" },
  cardTitle: { fontWeight: 700, fontSize: 13, color: "#2e7d32", marginBottom: 8 },
  th: { padding: "6px 6px", textAlign: "left", fontWeight: 700, color: "#1b5e20", fontSize: 11, borderBottom: "2px solid #c8e6c9" },
  td: { padding: "5px 6px", borderBottom: "1px solid #f1f8e9", fontSize: 12 },
};

export const ov = {
  bg: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.45)", zIndex: 100, overflowY: "auto", padding: "16px 8px" },
  box: { maxWidth: 860, margin: "0 auto", borderRadius: 14, overflow: "hidden" },
  confirmBg: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", zIndex: 200, display: "flex", alignItems: "center", justifyContent: "center", padding: 16 },
};
